#ifndef __EFI_STORAGE_WRITE_PROTECT_H__
#define __EFI_STORAGE_WRITE_PROTECT_H__

//
// Global GUID for the Storage Write Protect Protocol
//
#define EFI_STORAGE_WRITEPROTECT_PROTOCOL_GUID {0xAE1CDD2B, 0xB59A, 0x413A, { 0x8D, 0xFF, 0x56, 0xD2, 0xFC, 0x63, 0xB7, 0xE0 } }

#define EFI_STORAGE_WRITEPROTECT_PROTOCOL_REVISION 0x0000000000010000

//
// Declare forward reference to the Storage Write Protect Protocol
//
typedef struct _EFI_STORAGE_WRITEPROTECT_PROTOCOL   EFI_STORAGE_WRITEPROTECT_PROTOCOL;

typedef enum _EFI_WRITEPROTECT_TYPE
{
   NOT_WRITE_PROTECTED = 0x00,
   WRITE_PROTECTED     = 0x01,
   UNKNOWN_0           = 0x02,
   UNKNOWN_1           = 0x04,
   UNKNOWN_2           = 0x08,
   UNKNOWN_3           = 0x10,
   UNKNOWN_4           = 0x20
} EFI_WRITEPROTECT_TYPE;

typedef struct _EFI_WRITEPROTECT_ENTRY
{
   EFI_WRITEPROTECT_TYPE WpType;
   UINT64 Lba;
   UINT32 NumBlocks;
} EFI_WRITEPROTECT_ENTRY;

typedef struct _EFI_WRITEPRPOTECT_CONFIG
{
   UINT8 NumEntries;
   EFI_WRITEPROTECT_ENTRY *WpEntries;
} EFI_WRITEPROTECT_CONFIG;

typedef
EFI_STATUS
(EFIAPI * EFI_GET_SUPPORTED_WP_TYPES)(
   IN EFI_STORAGE_WRITEPROTECT_PROTOCOL *This,
   OUT UINT32 *LbaWpTypes
);

typedef
EFI_STATUS
(EFIAPI * EFI_SET_LU_WRITE_PROTECT)(
   IN EFI_STORAGE_WRITEPROTECT_PROTOCOL *This
);

typedef
EFI_STATUS
(EFIAPI * EFI_SET_LBA_WRITE_PROTECT)(
   IN EFI_STORAGE_WRITEPROTECT_PROTOCOL *This,
   IN EFI_WRITEPROTECT_CONFIG *WpConfig
);

typedef
EFI_STATUS
(EFIAPI * EFI_CLEAR_WRITE_PROTECT)(
   IN EFI_STORAGE_WRITEPROTECT_PROTOCOL *This
);

typedef
EFI_STATUS
(EFIAPI * EFI_GET_LU_WP_INFO)(
   IN EFI_STORAGE_WRITEPROTECT_PROTOCOL *This,
   OUT EFI_WRITEPROTECT_CONFIG *ProtectInfo
);

//
// Define Protocol Functions
//
struct _EFI_STORAGE_WRITEPROTECT_PROTOCOL
{
   UINT64 Revision;
   EFI_GET_SUPPORTED_WP_TYPES GetSupportedLbaWriteProtectTypes;
   EFI_SET_LU_WRITE_PROTECT SetLUWriteProtect;
   EFI_SET_LBA_WRITE_PROTECT SetLbaWriteProtect;
   EFI_CLEAR_WRITE_PROTECT ClearWriteProtect;
   EFI_GET_LU_WP_INFO GetLUWriteProtectInfo;
};

extern EFI_GUID gEfiStorageWriteProtectProtocolGuid;

#endif /* _EFI_STORAGE_WRITE_PROTECT_H_ */
